import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const marketplaceLink = 'https://github.com/larazan/laravel_marketplace'
  const allbirdsLink = ''
  const ecommLink = 'https://github.com/larazan/larashop'
  const quotaLink = 'https://github.com/larazan/whatAwords_client'
  const dispatchLink = 'https://react-dispatch.vercel.app/'
  const leafletLink = 'https://react-leaflet-eight.vercel.app/'
  const foodLink = 'https://github.com/larazan/flutter_food'

  return (
    <>
      <Head>
        <title>Zamroni CV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
         {/* Page */}
      <div className="mx-auto page max-w-3xl print:max-w-a4 md:max-w-a4 md:h-letter2 xsm:p-8 sm:p-9 md:pt-16 bg-white">
        {/* Name */}
        <div className='flex justify-between items-center'>
        <header className="flex items-center">
          <div
            className="initials-container mr-5 text-base leading-none text-white bg-gray-700 font-medium print:bg-black px-3"
            style={{ paddingBottom: "0.6875rem", paddingTop: "0.6875rem" }}
          >
            <div
              className="initial text-center"
              style={{ paddingBottom: "0.1875rem" }}
            >
              M
            </div>
            <div className="text-center initial">Z</div>
          </div>
          <h1 className="text-2xl font-semibold text-gray-750 pb-px">
            Moch Zamroni
          </h1>
          
        </header>
        <nav>
          <Link href={'/portofolio'}>
          <div className='flex px-4 py-2 items-center bg-gray-100 rounded-md font-bold cursor-pointer hover:bg-gray-150 hover:border'>
            Portofolio
          </div>
          </Link>
        </nav>
        </div>
       
        {/* end Name */}
      </div>
      {/* end Page */}

      {/* Page */}
      <div className="p-6 mx-auto page max-w-3xl print:max-w-a4 md:max-w-a4 md:h-a4 xsm:p-8 sm:p-9 md:p-12 print:bg-white bg-gray-100">
        {/* Column */}
        <div className="md:col-count-2 print:col-count-2 col-gap-md md:h-a4-col-full print:h-a4-col-full col-fill-auto">
          <section className="mt-2 first:mt-0">
            {/* To keep in the same column */}
            <div className="break-inside-avoid">
              <h2 className="mb-4 font-bold tracking-widest text-sm2 text-gray-550 print:font-normal">
                ABOUT ME
              </h2>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    Fullstack Developer
                  </h3>
                  <p className="leading-normal text-md text-gray-650">Since 2018</p>
                </header>
                <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  Mampu bekerja menggunakan berbagai framework terutama
                  Codeigniter, Laravel, dan Nextjs dengan menggunakan Mysql atau
                  Mongodb sebagai databasenya. untuk Mobile Apps memakai Flutter dengan
                  REST API
                </p>
              </section>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    User Interface Designer
                  </h3>
                  <p className="leading-normal text-md text-gray-650">Since 2017</p>
                </header>
                <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  Terbiasa menggunakan TailwindCss untuk hasil desain website
                  cepat dan modern serta Flutter sebagai UI/UX desain untuk
                  mobile apps.
                </p>
              </section>
            </div>
          </section>

          <section className="mt-8 first:mt-0">
            {/* To keep in the same column */}
            <div className="break-inside-avoid">
              <h2 className="mb-4 font-bold tracking-widest text-sm2 text-gray-550 print:font-normal">
                EXPERIENCE
              </h2>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    Wiklan.com
                  </h3>
                  <p className="leading-normal text-md text-gray-650">
                    Maret 2018 – 2020 | Web Developer
                  </p>
                </header>
                <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  Membuat proses input lokasi dengan Gmap, fitur chat, proses add to cart, fitur proses validasi dan verifikasi, fitur order, fitur pencarian dan lain-lain.
                </p>
              </section>
            </div>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  Match Advertising
                </h3>
                <p className="leading-normal text-md text-gray-650">
                  Desember 2017 – Februari 2018 | Web Developer
                </p>
              </header>
              <ul className="">
                <li className="mt-2.1 text-md text-gray-700 leading-normal">
                  Membuat sistem visit untuk marketing berdasarkan lokasi
                </li>
              </ul>
            </section>
          </section>

          <section className="mt-8 first:mt-0">
            {/* To keep in the same column */}
            <div className="break-inside-avoid">
              <h2 className="mb-4 font-bold tracking-widest text-sm2 text-gray-550 print:font-normal">
                EDUCATION
              </h2>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    SMA Negeri 11 Surabaya
                  </h3>
                  <p className="leading-normal text-md text-gray-650">
                    2001 – 2004
                  </p>
                </header>
              </section>
            </div>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  SMP Negeri 26 Surabaya
                </h3>
                <p className="leading-normal text-md text-gray-650">1998 – 2001</p>
              </header>
            </section>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  SD Muhammadiyah 14 Surabaya
                </h3>
                <p className="leading-normal text-md text-gray-650">1992 – 1998</p>
              </header>
            </section>
          </section>

          <section className="mt-8 first:mt-0">
            {/* To keep in the same column */}
            <div className="break-inside-avoid">
              <h2 className="mb-4 font-bold tracking-widest text-sm2 text-gray-550 print:font-normal">
                PROJECTS
              </h2>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    <a href="https://www.wiklan.com/" className="group" rel="noopener noreferrer">
                      Wiklan.com
                      <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                        ↗
                      </span>
                    </a>
                  </h3>
                  <p className="leading-normal text-md text-gray-650">
                    2018 | Codeigniter
                  </p>
                </header>
                <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  PT. Wijaya Iklan Indonesia (Wiklan.com) adalah sebuah
                  Marketplace Media Periklanan Terdepan dan Terlengkap di
                  Indonesia yang berpusat di Surabaya, 
                  menyediakan beragam jenis dan lokasi media iklan luar ruang
                  yang tersebar di seluruh Indonesia.
                </p>
              </section>
            </div>

            {/* <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  <a href="https://covid19-worlds.netlify.app/" className="group">
                    Covid Tracker
                    <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                      ↗
                    </span>
                  </a>
                </h3>
                <p className="leading-normal text-md text-gray-650">2020 | React</p>
              </header>
            </section>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  <a href="https://netflix-cl.netlify.app/" className="group">
                    Netflix Homepage
                    <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                      ↗
                    </span>
                  </a>
                </h3>
                <p className="leading-normal text-md text-gray-650">2020 | React</p>
              </header>
            </section>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  <a href="https://hulu-cl.netlify.app/" className="group">
                    Hulu Homepage
                    <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                      ↗
                    </span>
                  </a>
                </h3>
                <p className="leading-normal text-md text-gray-650">2020 | React</p>
              </header>
            </section> */}

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  <a target="_blank" href={quotaLink} className="group" rel="noopener noreferrer">
                    Qoutas
                    <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                      ↗
                    </span>
                  </a>
                </h3>
                <p className="leading-normal text-md text-gray-650">
                  2021 | React, Node
                </p>
              </header>
              <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  Proyek MERN (Mongodb, Express, React, Node) kumpulan Quote, yang bisa diedit backgound, jenis font sebelum didownload berupa gambar untuk konten media sosial.
                </p>
            </section>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  <a target="_blank" href={marketplaceLink} className="group" rel="noopener noreferrer">
                    Marketplace
                    <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                      ↗
                    </span>
                  </a>
                </h3>
                <p className="leading-normal text-md text-gray-650">
                  2022 | Laravel
                </p>
              </header>
              <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  Proyek Marketplace dari UWK Surabaya khusus dikembangkan untuk UMKM yang bergerak di bidang pengolahan pangan biji sorgum beserta turunannya.
                </p>
            </section>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  <a target="_blank" href={leafletLink} className="group" rel="noopener noreferrer">
                  Map News UI UX
                    <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                      ↗
                    </span>
                  </a>
                </h3>
                <p className="leading-normal text-md text-gray-650">
                  2022 | React, TailwindCss, Leaflet
                </p>
              </header>
              <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  Aplikasi Sosial Media berikut titik lokasi Map dengan lebih dari 60 kategori digunakan untuk posting promosi, jual beli, atau suatu peristiwa secara real time dan lain-lain.
                </p>
            </section>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  <a target="_blank" href={dispatchLink} className="group" rel="noopener noreferrer">
                  Asia Movie DB 
                    <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                      ↗
                    </span>
                  </a>
                </h3>
                <p className="leading-normal text-md text-gray-650">
                  2022 | React, TailwindCss, Leaflet
                </p>
              </header>
              <p className="mt-2.1 text-md text-gray-700 leading-normal">
                  Aplikasi data film berikut para artis untuk mereview film, artikel perfilman dan podcast.
                </p>
            </section>
           
          </section>

          <section className="mt-8 first:mt-0">
            {/* To keep in the same column */}
            <div className="break-inside-avoid">
              <h2 className="mb-4 font-bold tracking-widest text-sm2 text-gray-550 print:font-normal">
                SKILLS
              </h2>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    PHP
                  </h3>
                </header>

                <div className="my-3.2 last:pb-1.5">
                  <ul className="flex flex-wrap text-md leading-relaxed -mr-1.6 -mb-1.6">
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      Codeigniter
                    </li>
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      Laravel
                    </li>
                  </ul>
                </div>
              </section>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    JavaScript
                  </h3>
                </header>

                <div className="my-3.2 last:pb-1.5">
                  <ul className="flex flex-wrap text-md leading-relaxed -mr-1.6 -mb-1.6">
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      Node
                    </li>
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      Express
                    </li>
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      React
                    </li>
                  </ul>
                </div>
              </section>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    Mobile
                  </h3>
                </header>

                <div className="my-3.2 last:pb-1.5">
                  <ul className="flex flex-wrap text-md leading-relaxed -mr-1.6 -mb-1.6">
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      Flutter
                    </li>
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      React Native
                    </li>
                  </ul>
                </div>
              </section>

              <section className="mb-4.5 break-inside-avoid">
                <header>
                  <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                    Database
                  </h3>
                </header>

                <div className="my-3.2 last:pb-1.5">
                  <ul className="flex flex-wrap text-md leading-relaxed -mr-1.6 -mb-1.6">
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      Mysql
                    </li>
                    <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                      MongoDB
                    </li>
                  </ul>
                </div>
              </section>
            </div>

            <section className="mb-4.5 break-inside-avoid">
              <header>
                <h3 className="text-lg font-semibold text-gray-700 leading-snugish">
                  Other
                </h3>
              </header>
              <div className="my-3.2 last:pb-1.5">
                <ul className="flex flex-wrap text-md leading-relaxed -mr-1.6 -mb-1.6">
                  <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                    Tailwind
                  </li>
                  <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                    Git
                  </li>
                  {/* <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                    Go
                  </li> */}
                  <li className="px-2.5 mr-1.6 mb-1.6 text-base text-gray-750 leading-relaxed print:bg-white print:border-inset bg-gray-250">
                    Python
                  </li>
                </ul>
              </div>
            </section>
          </section>

          <section className="mt-8 first:mt-0">
            {/* To keep in the same column */}
            <div className="break-inside-avoid">
              <h2 className="mb-4 font-bold tracking-widest text-sm2 text-gray-550 print:font-normal">
                CONTACT
              </h2>

              <section className="mb-4.5 break-inside-avoid">
                <ul className="list-inside pr-7">
                  {/* <li className="mt-1.5 leading-normal text-gray-700 text-md">
                    <a href="//webpraktikos.com" className="group">
                      webpraktikos.com
                      <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                        ↗
                      </span>
                    </a>
                  </li> */}
                  <li className="mt-1.5 leading-normal text-gray-700 text-md">
                    <a href="https://github.com/larazan" className="group" rel="noopener noreferrer">
                      github.com/larazan
                      <span className="inline-block text-gray-550 print:text-black font-normal group-hover:text-gray-700 transition duration-100 ease-in">
                        ↗
                      </span>
                    </a>
                  </li>
                  <li className="mt-1.5 leading-normal text-gray-700 text-md">
                    Balongsari blok 9c/5 Tandes, Surabaya
                  </li>
                  <li className="mt-1.5 leading-normal text-gray-700 text-md">
                    0896 5577 0894
                  </li>
                  <li className="mt-1.5 leading-normal text-gray-700 text-md">
                    purunjamu@gmail.com
                  </li>
                </ul>
              </section>
            </div>
          </section>
        </div>
        {/* end Column */}
      </div>
      {/* end Page */}
      </main>
    </>
  )
}
